version: '3'

services:

  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: simtalk

  web:
    container_name: simTalk
    build: .
    restart: always
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python -m scripts.fake && gunicorn -b 0.0.0.0:8080 simTalk.wsgi"
    volumes:
      - ../:/code/
      - static-volume:/code/simTalk/static
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - static-volume:/code/static/
      - ./config/nginx_web.nginx:/etc/nginx/conf.d/nginx_web.conf
    ports:
      - "80:8080"
    depends_on:
      - web

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
     - PMA_HOST=db
     - PMA_USER=root
     - PMA_PASSWORD=123456
    ports:
     - "8082:80"
    volumes:
     - /sessions

volumes:
  static-volume:
